<?php

declare(strict_types=1);

namespace Engine\Tests;

use DI\Container;
use DI\ContainerBuilder;
use PHPUnit\Framework\TestCase;
use OSM\MatchEngine\Exceptions\EngineException;
use OSM\MatchEngine\Helpers\PlayerBuilder;
use OSM\MatchEngine\Structures\Player;

abstract class TestBase extends TestCase
{
    /** @var Container */
    protected $container;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->container = ContainerBuilder::buildDevContainer();
    }

    /**
     * Creates standard player for tests in position
     *
     * @param string $pos
     * @return Player
     * @throws EngineException
     */
    public function getStandardPlayer(string $pos): Player
    {
        $player = PlayerBuilder::buildRandomPlayer($pos, 100, 100, 100);
        $player->perform(0);

        return $player;
    }
}